name: Homebrew Build and Publish

on:
  push:
    # tags:
    #   - '*'
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/runner/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Get sha256 and build package
        run: |
          formula_name="aws-deployer"
          formula_version=$(echo ${{ github.ref }} | cut -d / -f 3)
          package_name="$formula_name-$formula_version.tar.gz"
          package_sha=$(curl -sL https://github.com/sanoyo/aws-deployer/archive/${{ github.ref }}.tar.gz | shasum -a 256 | awk '{print $1}')

          sed -i '' "s/url.*/url \"https:\/\/github.com\/sanoyo\/aws-deployer\/archive\/${{ github.ref }}.tar.gz\"/" $formula_name.rb
          sed -i '' "s/sha256.*/sha256 \"$package_sha\"/" $formula_name.rb

          brew install --build-from-source $formula_name.rb

      - name: Publish package to Homebrew
        run: |
          brew update
          brew test $formula_name
          brew audit --strict $formula_name
          brew install --verbose $formula_name
          brew bottle --json $formula_name
          brew upload --verbose --json --retry $formula_name
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
